// SPDX-License-Identifier: GPL-3.0-or-later

//! The GIS readers against files written by other software: GeoTIFFs
//! from libtiff (through Pillow 11.3), a shapefile set from an
//! independent struct-level writer following the ESRI specification, and
//! GeoJSON. Generated by `make_fixtures.py` (kept out of the tree; the
//! values it wrote are restated in the assertions).

use std::path::PathBuf;

use stormsewer_swmm::gis::vector::{FieldKind, FieldValue, Geometry};
use stormsewer_swmm::gis::{geojson, geotiff, read_raster, read_vector, shapefile};

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/gis").join(name)
}

#[test]
fn libtiff_lzw_predictor2_uint16_with_utm_keys() {
    let g = geotiff::read(&fixture("dem_lzw_pred2_u16.tif")).unwrap();
    let r = &g.raster;
    assert_eq!((r.ncols, r.nrows), (6, 5));
    assert_eq!(r.cell, 2.0);
    assert_eq!((r.x0, r.y1()), (500000.0, 4000000.0));
    // value = 1000 + row*10 + col
    assert_eq!(r.get(0, 0), Some(1000.0));
    assert_eq!(r.get(5, 4), Some(1045.0));
    assert_eq!(r.get(3, 2), Some(1023.0));
    assert!(r.get(2, 1).unwrap().is_nan(), "65535 is the no-data value");
    assert_eq!(r.nodata, Some(65535.0));
    let crs = g.crs.unwrap();
    assert_eq!(crs.epsg, Some(32617));
    assert_eq!(crs.unit.to_metre, 1.0);
    assert!(g.info.contains("LZW") && g.info.contains("predictor 2") && g.info.contains("uint16"), "{}", g.info);
}

#[test]
fn libtiff_deflate_predictor3_float32_with_state_plane_feet() {
    let (r, crs) = read_raster(&fixture("dem_deflate_pred3_f32.tif")).unwrap();
    assert_eq!(r.cell, 5.0);
    assert_eq!((r.x0, r.y1()), (1449000.0, 542000.0));
    assert_eq!(r.y0, 542000.0 - 25.0);
    // value = 100.25 + row*1.5 + col*0.25 (exact in float32)
    assert_eq!(r.get(0, 0), Some(100.25));
    assert_eq!(r.get(5, 4), Some(100.25 + 6.0 + 1.25));
    assert_eq!(r.get(1, 3), Some(100.25 + 4.5 + 0.25));
    assert!(r.get(4, 3).unwrap().is_nan());
    let crs = crs.unwrap();
    assert_eq!(crs.epsg, Some(2264));
    assert_eq!(crs.unit.name, "US survey foot");
}

#[test]
fn libtiff_packbits_uint8_geographic_pixel_is_point() {
    let g = geotiff::read(&fixture("dem_packbits_u8.tif")).unwrap();
    let r = &g.raster;
    assert_eq!(r.get(5, 4), Some(10.0 + 24.0 + 5.0));
    assert_eq!(r.nodata, None);
    // RasterPixelIsPoint: the tiepoint names the centre of the top-left
    // cell, so the grid edge is half a cell further out.
    assert!((r.x0 - (-80.85 - 0.0005)).abs() < 1e-9, "{}", r.x0);
    assert!((r.y1() - (35.23 + 0.0005)).abs() < 1e-9, "{}", r.y1());
    let crs = g.crs.unwrap();
    assert!(crs.is_geographic());
    assert_eq!(crs.epsg, Some(4326));
    assert!(g.info.contains("PackBits"), "{}", g.info);
}

#[test]
fn libtiff_lzw_int32_with_model_transformation_and_user_defined_tm() {
    let g = geotiff::read(&fixture("dem_lzw_pred2_i32_xform.tif")).unwrap();
    let r = &g.raster;
    assert_eq!(r.cell, 3.0);
    assert_eq!((r.x0, r.y1()), (1000.0, 2000.0));
    // value = -50 + row*100 + col*3
    assert!(r.get(0, 0).unwrap().is_nan());
    assert_eq!(r.get(1, 0), Some(-47.0));
    assert_eq!(r.get(5, 4), Some(-50.0 + 400.0 + 15.0));
    assert_eq!(r.get(2, 2), Some(156.0));
    // ProjectedCSType 32767 with ProjCoordTrans 1 and UTM parameters is
    // identified as WGS 84 / UTM zone 17N by its constants.
    let crs = g.crs.unwrap();
    assert_eq!(crs.epsg, Some(32617), "{crs:?}");
    assert!(g.info.contains("int32"), "{}", g.info);
}

#[test]
fn independent_shapefile_points_with_every_dbf_type_and_utf8_cpg() {
    let l = shapefile::read(&fixture("manholes.shp")).unwrap();
    assert_eq!(l.features.len(), 3);
    let names: Vec<&str> = l.fields.iter().map(|f| f.name.as_str()).collect();
    assert_eq!(names, ["NAME", "INVERT", "RIM", "GATED", "BUILT"]);
    assert_eq!(l.fields[1].kind, FieldKind::Number);
    assert_eq!(l.fields[3].kind, FieldKind::Bool);
    assert_eq!(l.fields[4].kind, FieldKind::Date);
    assert_eq!(l.features[0].geometry, Some(Geometry::Point(1449620.4, 542689.1)));
    assert_eq!(l.value(0, "NAME"), Some(&FieldValue::Text("MH-1".into())));
    assert_eq!(l.value(0, "INVERT"), Some(&FieldValue::Number(700.25)));
    assert_eq!(l.value(0, "GATED"), Some(&FieldValue::Bool(true)));
    assert_eq!(l.value(0, "BUILT"), Some(&FieldValue::Date("20200517".into())));
    assert_eq!(l.value(1, "RIM"), Some(&FieldValue::Null), "blank numeric is null");
    assert_eq!(l.value(1, "GATED"), Some(&FieldValue::Bool(false)));
    assert_eq!(l.value(2, "NAME"), Some(&FieldValue::Text("Caf\u{e9}".into())), "UTF-8 per the .cpg");
    assert_eq!(l.value(2, "GATED"), Some(&FieldValue::Null));
    let crs = l.crs.as_ref().expect("prj parsed");
    assert_eq!(crs.epsg, Some(2264), "ESRI prj identified by its parameters");
    assert!(l.crs_text.as_deref().unwrap().starts_with("PROJCS"));
    assert_eq!(l.bounds(), Some((1449620.4, 542689.1, 1449820.4, 542789.1)));
}

#[test]
fn independent_shapefile_polylines_with_a_multipart_record() {
    let l = read_vector(&fixture("pipes.shp")).unwrap();
    assert_eq!(l.features.len(), 2);
    match &l.features[0].geometry {
        Some(Geometry::LineString(p)) => assert_eq!(p.len(), 3),
        other => panic!("{other:?}"),
    }
    match &l.features[1].geometry {
        Some(Geometry::MultiLineString(parts)) => {
            assert_eq!(parts.len(), 2);
            assert_eq!(parts[1][0], (1449900.0, 542800.0));
        }
        other => panic!("{other:?}"),
    }
    assert_eq!(l.value(0, "DIAM"), Some(&FieldValue::Number(24.0)));
    assert_eq!(l.value(1, "N"), Some(&FieldValue::Number(0.012)));
    // Reading the .shx is not needed, but it is consistent with the .shp.
    let shx = std::fs::read(fixture("pipes.shx")).unwrap();
    assert_eq!(shapefile::shape_type(&shx).unwrap(), 3);
    assert_eq!(shx.len(), 100 + 8 * 2);
}

#[test]
fn geojson_fixtures_with_and_without_a_crs_member() {
    let b = geojson::read(&fixture("basins.geojson")).unwrap();
    assert_eq!(b.crs.as_ref().and_then(|c| c.epsg), Some(2264));
    assert_eq!(b.features.len(), 2);
    let b1 = b.features[0].geometry.as_ref().unwrap();
    assert!((b1.area() - (660.0 * 660.0 - 100.0 * 100.0)).abs() < 1e-6);
    assert_eq!(b1.outer_ring().unwrap().len(), 4);
    let b2 = b.features[1].geometry.as_ref().unwrap();
    assert!(matches!(b2, Geometry::MultiPolygon(_)));
    assert_eq!(b2.outer_ring().unwrap().len(), 3, "the larger part");
    assert_eq!(b.value(0, "imperv"), Some(&FieldValue::Number(45.5)));
    let g = read_vector(&fixture("gages_wgs84.geojson")).unwrap();
    assert_eq!(g.crs.as_ref().and_then(|c| c.epsg), Some(4326), "RFC 7946 default");
    assert_eq!(g.value(0, "id"), Some(&FieldValue::Text("RG1".into())));
    assert_eq!(g.value(0, "station"), Some(&FieldValue::Text("CLT".into())));
}
