// SPDX-License-Identifier: GPL-3.0-or-later

//! A plain document PDF: headings, paragraphs, key/value tables, ruled
//! tables, tagged lists and monospace blocks, with a header band and page
//! numbers on every page. The design report in [`super::pdf`] draws its
//! own schedules and schematics from a project; this writer takes content
//! that is already text — the SWMM model report — and lays it out.

use std::fs::File;
use std::io::BufWriter;
use std::path::Path;

use printpdf::{
    BuiltinFont, Color, IndirectFontRef, Line, Mm, PdfDocument, PdfDocumentReference,
    PdfLayerReference, Point, Rgb,
};

const PAGE_W: f32 = 215.9;
const PAGE_H: f32 = 279.4;
const MARGIN_L: f32 = 18.0;
const MARGIN_R: f32 = 18.0;
const HEADER_TOP: f32 = PAGE_H - 14.0;
const CONTENT_TOP: f32 = PAGE_H - 30.0;
const FOOTER_Y: f32 = 12.0;
const CONTENT_BOTTOM: f32 = 20.0;
const TEXT_W: f32 = PAGE_W - MARGIN_L - MARGIN_R;

/// One piece of a document.
#[derive(Clone, Debug, PartialEq)]
pub enum PdfBlock {
    Heading(String),
    Paragraph(String),
    KeyValues(Vec<(String, String)>),
    Table {
        title: String,
        columns: Vec<String>,
        rows: Vec<Vec<String>>,
        note: Option<String>,
    },
    /// Tagged lines: the tag is set in bold before the text.
    List(Vec<(String, String)>),
    /// Verbatim monospace lines. Long lines are cut at the page edge.
    Mono(String),
}

fn ink() -> Color {
    Color::Rgb(Rgb::new(0.13, 0.16, 0.20, None))
}
fn muted() -> Color {
    Color::Rgb(Rgb::new(0.45, 0.48, 0.52, None))
}
fn rule_color() -> Color {
    Color::Rgb(Rgb::new(0.72, 0.74, 0.77, None))
}

/// Millimetres per character: Courier is fixed at 0.6 em.
fn mono_w(chars: usize, pt: f32) -> f32 {
    chars as f32 * pt * 0.6 * 0.352_778
}

/// Approximate proportional text width (Helvetica averages ~0.5 em).
fn prop_w(text: &str, pt: f32) -> f32 {
    text.chars().count() as f32 * pt * 0.5 * 0.352_778
}

/// Greedy word wrap to `width` mm at `pt`, breaking over-long words.
fn wrap(text: &str, pt: f32, width: f32) -> Vec<String> {
    let mut lines = Vec::new();
    for para in text.split('\n') {
        let mut line = String::new();
        for word in para.split_whitespace() {
            let candidate = if line.is_empty() {
                word.to_string()
            } else {
                format!("{line} {word}")
            };
            if prop_w(&candidate, pt) <= width {
                line = candidate;
            } else {
                if !line.is_empty() {
                    lines.push(std::mem::take(&mut line));
                }
                let mut w = word.to_string();
                while prop_w(&w, pt) > width && w.chars().count() > 1 {
                    let cut = ((width / (pt * 0.5 * 0.352_778)) as usize).max(1);
                    let head: String = w.chars().take(cut).collect();
                    lines.push(head);
                    w = w.chars().skip(cut).collect();
                }
                line = w;
            }
        }
        lines.push(line);
    }
    lines
}

struct Fonts {
    body: IndirectFontRef,
    bold: IndirectFontRef,
    mono: IndirectFontRef,
}

struct Pager<'a> {
    doc: &'a PdfDocumentReference,
    layer: PdfLayerReference,
    fonts: &'a Fonts,
    title: &'a str,
    subtitle: &'a str,
    y: f32,
    page_no: u32,
}

impl Pager<'_> {
    fn hline(layer: &PdfLayerReference, x1: f32, x2: f32, y: f32, color: Color, w: f32) {
        layer.set_outline_color(color);
        layer.set_outline_thickness(w);
        layer.add_line(Line {
            points: vec![
                (Point::new(Mm(x1), Mm(y)), false),
                (Point::new(Mm(x2), Mm(y)), false),
            ],
            is_closed: false,
        });
    }

    fn stamp_chrome(&mut self) {
        let l = &self.layer;
        let right = PAGE_W - MARGIN_R;
        l.set_fill_color(ink());
        let title: String = self.title.chars().take(90).collect();
        l.use_text(&title, 11.0, Mm(MARGIN_L), Mm(HEADER_TOP), &self.fonts.bold);
        l.set_fill_color(muted());
        if !self.subtitle.trim().is_empty() {
            let sub: String = self.subtitle.chars().take(140).collect();
            l.use_text(&sub, 7.5, Mm(MARGIN_L), Mm(HEADER_TOP - 5.0), &self.fonts.body);
        }
        Self::hline(l, MARGIN_L, right, HEADER_TOP - 8.0, rule_color(), 0.5);
        l.set_fill_color(muted());
        l.use_text(
            "Generated by StormSewer — free, open-source storm sewer design",
            6.5,
            Mm(MARGIN_L),
            Mm(FOOTER_Y),
            &self.fonts.body,
        );
        let pn = format!("Page {}", self.page_no);
        let pw = mono_w(pn.chars().count(), 6.5) * 0.92;
        l.use_text(&pn, 6.5, Mm(right - pw), Mm(FOOTER_Y), &self.fonts.body);
        l.set_fill_color(ink());
    }

    fn new_page(&mut self) {
        let (page, layer) = self.doc.add_page(Mm(PAGE_W), Mm(PAGE_H), "content");
        self.layer = self.doc.get_page(page).get_layer(layer);
        self.page_no += 1;
        self.y = CONTENT_TOP;
        self.stamp_chrome();
    }

    fn ensure(&mut self, need: f32) {
        if self.y - need < CONTENT_BOTTOM {
            self.new_page();
        }
    }

    fn heading(&mut self, text: &str) {
        self.ensure(20.0);
        self.y -= 4.0;
        self.layer.set_fill_color(ink());
        self.layer
            .use_text(text, 10.5, Mm(MARGIN_L), Mm(self.y), &self.fonts.bold);
        self.y -= 2.2;
        Self::hline(&self.layer, MARGIN_L, PAGE_W - MARGIN_R, self.y, rule_color(), 0.4);
        self.y -= 4.4;
    }

    fn subheading(&mut self, text: &str) {
        self.ensure(14.0);
        self.y -= 2.0;
        self.layer.set_fill_color(ink());
        self.layer
            .use_text(text, 9.0, Mm(MARGIN_L), Mm(self.y), &self.fonts.bold);
        self.y -= 4.6;
    }

    fn line(&mut self, text: &str, pt: f32, color: Color, font: &IndirectFontRef, x: f32) {
        self.ensure(pt * 0.6);
        self.layer.set_fill_color(color);
        self.layer.use_text(text, pt, Mm(x), Mm(self.y), font);
        self.layer.set_fill_color(ink());
        self.y -= pt * 0.55;
    }

    fn paragraph(&mut self, text: &str, pt: f32, color: Color) {
        let font = self.fonts.body.clone();
        for l in wrap(text, pt, TEXT_W) {
            self.line(&l, pt, color.clone(), &font, MARGIN_L);
        }
        self.y -= 1.5;
    }

    fn key_values(&mut self, kv: &[(String, String)]) {
        const PT: f32 = 8.0;
        let key_w = 52.0_f32;
        for (k, v) in kv {
            let lines = wrap(v, PT, TEXT_W - key_w - 2.0);
            self.ensure(PT * 0.55 * lines.len() as f32 + 1.0);
            let bold = self.fonts.bold.clone();
            let body = self.fonts.body.clone();
            let y0 = self.y;
            self.layer.set_fill_color(ink());
            self.layer
                .use_text(k, PT, Mm(MARGIN_L), Mm(y0), &bold);
            for (i, l) in lines.iter().enumerate() {
                if i > 0 {
                    self.ensure(PT * 0.6);
                }
                self.layer
                    .use_text(l, PT, Mm(MARGIN_L + key_w), Mm(self.y), &body);
                self.y -= PT * 0.55;
            }
            self.y -= 0.6;
            Self::hline(&self.layer, MARGIN_L, PAGE_W - MARGIN_R, self.y + 1.2, rule_color(), 0.15);
        }
        self.y -= 2.0;
    }

    fn table(&mut self, columns: &[String], rows: &[Vec<String>]) {
        const ROW_H: f32 = 4.6;
        const PT: f32 = 7.0;
        if columns.is_empty() {
            return;
        }
        // Column widths from the longest cell, scaled to the text width,
        // with a floor so a narrow column still shows its heading start.
        let n = columns.len();
        let mut chars: Vec<usize> = columns.iter().map(|c| c.chars().count().max(3)).collect();
        for r in rows {
            for (i, c) in r.iter().enumerate().take(n) {
                chars[i] = chars[i].max(c.chars().count());
            }
        }
        let total: usize = chars.iter().sum::<usize>() + n * 2;
        let per_char = (TEXT_W / total as f32).min(mono_w(1, PT));
        let widths: Vec<f32> = chars.iter().map(|c| (*c + 2) as f32 * per_char).collect();
        let fit = |text: &str, width: f32| -> String {
            let max = ((width / per_char) as usize).saturating_sub(1).max(1);
            if text.chars().count() > max {
                text.chars().take(max).collect()
            } else {
                text.to_string()
            }
        };
        let numeric = |s: &str| s.trim().parse::<f64>().is_ok();

        let header = |p: &mut Pager<'_>| {
            p.ensure(ROW_H * 3.0);
            let mut x = MARGIN_L;
            p.layer.set_fill_color(ink());
            let bold = p.fonts.bold.clone();
            for (c, w) in columns.iter().zip(&widths) {
                p.layer
                    .use_text(fit(c, *w), 6.5, Mm(x), Mm(p.y), &bold);
                x += w;
            }
            p.y -= 1.6;
            Self::hline(&p.layer, MARGIN_L, PAGE_W - MARGIN_R, p.y, ink(), 0.5);
            p.y -= ROW_H * 0.85;
        };
        header(self);
        let mono = self.fonts.mono.clone();
        for row in rows {
            if self.y - ROW_H < CONTENT_BOTTOM {
                self.new_page();
                header(self);
            }
            let mut x = MARGIN_L;
            for (i, w) in widths.iter().enumerate() {
                let cell = row.get(i).map(String::as_str).unwrap_or("");
                let text = fit(cell, *w);
                let tx = if numeric(cell) && i > 0 {
                    x + w - 2.0 - mono_w(text.chars().count(), PT)
                } else {
                    x
                };
                self.layer
                    .use_text(&text, PT, Mm(tx), Mm(self.y), &mono);
                x += w;
            }
            self.y -= 1.4;
            Self::hline(&self.layer, MARGIN_L, PAGE_W - MARGIN_R, self.y, rule_color(), 0.2);
            self.y -= ROW_H - 1.4;
        }
        self.y -= 2.0;
    }

    fn list(&mut self, items: &[(String, String)]) {
        const PT: f32 = 8.0;
        let bold = self.fonts.bold.clone();
        let body = self.fonts.body.clone();
        for (tag, text) in items {
            let tag_w = prop_w(tag, PT) + 3.0;
            let lines = wrap(text, PT, TEXT_W - tag_w);
            self.ensure(PT * 0.55 * lines.len() as f32);
            self.layer.set_fill_color(ink());
            self.layer
                .use_text(tag, PT, Mm(MARGIN_L), Mm(self.y), &bold);
            for (i, l) in lines.iter().enumerate() {
                if i > 0 {
                    self.ensure(PT * 0.6);
                }
                self.layer
                    .use_text(l, PT, Mm(MARGIN_L + tag_w), Mm(self.y), &body);
                self.y -= PT * 0.55;
            }
        }
        self.y -= 1.5;
    }

    fn mono(&mut self, text: &str) {
        const PT: f32 = 6.5;
        let max = (TEXT_W / mono_w(1, PT)) as usize;
        let mono = self.fonts.mono.clone();
        for raw in text.lines() {
            let line = raw.replace('\t', "    ");
            let shown: String = if line.chars().count() > max {
                line.chars().take(max.saturating_sub(1)).chain(std::iter::once('…')).collect()
            } else {
                line
            };
            self.line(&shown, PT, ink(), &mono, MARGIN_L);
        }
        self.y -= 1.5;
    }
}

/// Write `blocks` as a PDF at `path`.
pub fn export_document_pdf(
    title: &str,
    subtitle: &str,
    blocks: &[PdfBlock],
    path: &Path,
) -> Result<(), String> {
    let (doc, page1, layer1) = PdfDocument::new(title, Mm(PAGE_W), Mm(PAGE_H), "content");
    let fonts = Fonts {
        body: doc.add_builtin_font(BuiltinFont::Helvetica).map_err(|e| e.to_string())?,
        bold: doc.add_builtin_font(BuiltinFont::HelveticaBold).map_err(|e| e.to_string())?,
        mono: doc.add_builtin_font(BuiltinFont::Courier).map_err(|e| e.to_string())?,
    };
    let layer = doc.get_page(page1).get_layer(layer1);
    let mut p = Pager {
        doc: &doc,
        layer,
        fonts: &fonts,
        title,
        subtitle,
        y: CONTENT_TOP,
        page_no: 1,
    };
    p.stamp_chrome();
    for b in blocks {
        match b {
            PdfBlock::Heading(h) => p.heading(h),
            PdfBlock::Paragraph(t) => p.paragraph(t, 8.5, ink()),
            PdfBlock::KeyValues(kv) => p.key_values(kv),
            PdfBlock::Table {
                title,
                columns,
                rows,
                note,
            } => {
                p.subheading(title);
                if let Some(n) = note {
                    p.paragraph(n, 7.5, muted());
                }
                p.table(columns, rows);
            }
            PdfBlock::List(items) => p.list(items),
            PdfBlock::Mono(t) => p.mono(t),
        }
    }
    let file = File::create(path).map_err(|e| format!("cannot create {}: {e}", path.display()))?;
    doc.save(&mut BufWriter::new(file)).map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn wraps_words_and_cuts_long_ones() {
        let lines = wrap("one two three four five six seven eight nine ten", 8.0, 30.0);
        assert!(lines.len() > 1);
        assert!(lines.iter().all(|l| prop_w(l, 8.0) <= 30.0 + 1e-3), "{lines:?}");
        let long = "x".repeat(400);
        let lines = wrap(&long, 8.0, 40.0);
        assert!(lines.len() > 5);
        assert!(lines.iter().all(|l| prop_w(l, 8.0) <= 40.0 + 1e-3));
        assert_eq!(wrap("a\n\nb", 8.0, 50.0), vec!["a", "", "b"]);
    }

    #[test]
    fn writes_a_multi_page_document() {
        let dir = std::env::temp_dir().join("stormsewer-tests");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("pdf_doc.pdf");
        let rows: Vec<Vec<String>> = (0..120)
            .map(|i| vec![format!("J{i}"), format!("{}", i as f64 * 0.5), "JUNCTION".into()])
            .collect();
        let blocks = vec![
            PdfBlock::Heading("Engine".into()),
            PdfBlock::KeyValues(vec![
                ("Engine".into(), "EPA SWMM 5.2.4".into()),
                ("SHA-256".into(), "ab".repeat(32)),
            ]),
            PdfBlock::Paragraph("A paragraph ".repeat(40)),
            PdfBlock::List(vec![("WARNING".into(), "something ".repeat(30))]),
            PdfBlock::Table {
                title: "Node Depth Summary".into(),
                columns: vec!["Node".into(), "Depth".into(), "Type".into()],
                rows,
                note: Some("all nodes".into()),
            },
            PdfBlock::Mono("[TITLE]\nline\n\t tabbed\n".to_string() + &"y".repeat(300)),
        ];
        export_document_pdf("Report", "subtitle", &blocks, &path).unwrap();
        let bytes = std::fs::read(&path).unwrap();
        assert!(bytes.starts_with(b"%PDF"));
        // 120 table rows at ~4.6 mm need more than one page.
        let text = String::from_utf8_lossy(&bytes);
        assert!(text.matches("/Type /Page\n").count() >= 2 || text.matches("/Type /Page ").count() >= 2 || bytes.len() > 20_000);
    }
}
